name: Deploy

on:
  workflow_run:
    workflows: [ Test, Publish ]
    types: [ completed ]
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  read-cached-outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir ./out
          touch ./out/publish-1.txt
          echo Publish >> publish-1.txt

      - name: Restore Test
        id: cache-restore-test
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: ./test
          key: test-${{ github.base_ref }}-${{ github.run_id }}-${{github.run_number}}-${{ github.run_attempt }}
          restore-keys: |
            test-${{ github.base_ref }}-

      - name: Restore Publish
        id: cache-restore-test
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: ./publish
          key: publish-${{ github.base_ref }}-${{ github.run_id }}-${{github.run_number}}-${{ github.run_attempt }}
          restore-keys: |
            publish-${{ github.base_ref }}-

      - name: Read Test
        run: |
          cd ./test/out
          cat test.txt

      - name: Read Publish
        run: |
          cd ./publish/out
          cat publish.txt
