name: Dependent workflow

on:
  workflow_run:
    workflows: [ Parent workflow ]
    types: [ completed ]


jobs:
  dependent:
    runs-on: ubuntu-latest
    steps:
      - run: echo Child
      - run: echo ${{ github.event.workflow_run.id }}
