name: Test

on:
  push:
    branches:
      - main

jobs:
  create-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir ./out
          touch ./out/test.txt
          echo ${{ github.run_id }}/${{github.run_number}}/${{github.run_attempt}} >> test.txt

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ./out

      - name: Cache
        uses: actions/cache/save@v4
        with:
          path: ./out
          key: test-${{ github.base_ref }}-${{ github.run_id }}-${{github.run_number}}-${{ github.run_attempt }}
